version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always #container reinicia se morrer
    ports:
      - 2345:5432
    env_file:
      - .env #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    networks:
      - repo_provas_network
    volumes:
      - postgres:/var/lib/postgresql/data

  app_node:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db # só sobe quando o postgres tiver no ar
    env_file:
      - .env #configurar DATABASE_URL
    networks:
      - repo_provas_network
    # entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

networks:
  repo_provas_network:
    driver: bridge
volumes: 
  postgres: