version: "3"
services:
  db:
    image: postgres:13
    container_name: db
    restart: always #container reinicia se morrer
    ports:
      - 2345:5432
    env_file:
      - .env.test #configurar POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    networks:
      - repo_provas_network

  app_node:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db # só sobe quando o postgres tiver no ar
    env_file:
      - .env.test #configurar DATABASE_URL
    networks:
      - repo_provas_network
    # entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run test"

networks:
  repo_provas_network:
    driver: bridge